### PR TITLE
DOC: fix docstrings

### PR DESCRIPTION
**Pull request by scottclowe**
Tidy up all the docstrings. Fix some entries which were mistaken, add some missing returns, otherwise clarify text or change to match numpy documentation styleguide recommendations.

### CODE REVIEW

**Comment by scottclowe** [comment]
Sander, do you want to look over these docstring changes? Or are you happy to sanction me changing them without reading them?

**Comment by scottclowe** [comment]
Note: I think this is the last PR for 0.5.3. After that, further changes will be going into 0.6.0.

**Comment by swkeemink** [comment]
I'll have a look this weekend. I also need to do a re-install on Windows and add an example Python file, for #24, before we increment to 0.6.0.

**Comment by scottclowe** [comment]
I fixed tiff/TIFF and "dimenisons". I didn't change the `image2array(image)` documentation because I will change the edge-case handling in this commit:
https://github.com/rochefort-lab/fissa/pull/36/commits/c46e1e7d9672b4e51656b44d68356dd4503bbbcb

**Pull request merged**
