### PR TITLE
JNB:DOC:RF: update Binder environment and move Suite2p example to different Binder

### PR DESCRIPTION
**Pull request by swkeemink**
With this update we add a separate Binder environment for Suite2p to avoid version incompatibilities with SIMA. Additionally we remove all the Suite2p dependencies from the standard Binder.

We also update the Binder environment to no longer have Holoviews dependencies, and use Matplotlib instead.

See [here](https://github.com/rochefort-lab/fissa-suite2p-example) for the Suite2p example repository, and [here](https://mybinder.org/v2/gh/rochefort-lab/fissa-suite2p-example/master?filepath=.%2FSuite2p%20example.ipynb) for the binder.

### CODE REVIEW

**Comment by scottclowe** [comment]
I think this PR should instead remove the suite2p notebook from the fissa repo entirely and change the README to link to the assets now in https://github.com/rochefort-lab/fissa-suite2p-example. It would be better not to have the notebook duplicated - we don't want to have to update it in two places.

**Comment by swkeemink** [comment]
> I think this PR should instead remove the suite2p notebook from the fissa repo entirely and change the README to link to the assets now in https://github.com/rochefort-lab/fissa-suite2p-example. It would be better not to have the notebook duplicated - we don't want to have to update it in two places.

Good point. Updated that now.

Should we also remove all mentions from `.appveyor.yml`, and perhaps somewhere else I'm forgetting in the testing backend?

**Comment by scottclowe** [comment]
> Should we also remove all mentions from .appveyor.yml,

No, we still run tests on AppVeyor. It is still free and we can run one Windows env on AppVeyor while we run another on GitHub.

> and perhaps somewhere else I'm forgetting in the testing backend?

I'm not sure what you are forgetting, so I don't know!

**Comment by swkeemink** [comment]
> > Should we also remove all mentions from .appveyor.yml,
> 
> No, we still run tests on AppVeyor. It is still free and we can run one Windows env on AppVeyor while we run another on GitHub.
> 
> > and perhaps somewhere else I'm forgetting in the testing backend?
> 
> I'm not sure what you are forgetting, so I don't know!

I meant removing the suite2p parts of it =)

And the tests seem to have failed which I assume is because of this!

**Comment by scottclowe** [comment]
> I meant removing the suite2p parts of it =)
> 
> And the tests seem to have failed which I assume is because of this!

Yes, we need to remove references to suite2p in the GitHub tests and AppVeyor tests. They are trying to remove the Suite2p notebook so they don't test it when testing the other notebooks, and it breaks when the notebook does not exist.

Please refactor the PR so you are just removing the Suite 2p HTML and not modifying it in one commit and then removing it in another (it is a large asset to add to the history).

Before this PR goes through, I will add a HTML redirect for the Suite 2p HTML to the new path in https://github.com/rochefort-lab/fissa-suite2p-example.

**Review by scottclowe — CHANGES_REQUESTED** [review]
Changes already requested in comments.

**Comment by swkeemink** [comment]
Refactored and updated the testing to not have Suite2p mentions (hopefully)

**Pull request merged**
