### PR TITLE
DOC: Add Suite2p example notebook

### PR DESCRIPTION
**Pull request by swkeemink**
In this pull request I add a notebook which shows how to combine FISSA with the Suite2p toolbox, as well as some small rewriting of the tutorial section of the readme.

### CODE REVIEW

**Comment by scottclowe** [comment]
All of these commits should have the DOC tag, since they are all affecting documentation. (ENH is only for new features, and MAINT is for code maintenance.)

**Comment by swkeemink** [comment]
> All of these commits should have the DOC tag, since they are all affecting documentation. (ENH is only for new features, and MAINT is for code maintenance.)

I was wondering about that, but since I added a new notebook (which is mostly code) I erred on the wrong side. It is indeed meant for documentation so should be DOC.

**Comment by scottclowe** [comment]
Will need to add `pip install suite2p` (and installing its dependencies) to the continuous integration script (.travis.yml) for the notebook tests.

**Comment by scottclowe** [comment]
Closes #83.

**Comment by scottclowe** [comment]
I made suggested changes here: https://github.com/swkeemink/fissa/pull/2

**Comment by scottclowe** [comment]
I rebased to fix the commit duplication due to a messed up merge, but the commits persisted even after I force-pushed over the source branch for the PR. I'm hence abandoning this PR and adding the desired content in #120.

**Pull request closed without merging**
